### PR TITLE
Fix the `Bitmap::<32>::mask(32)` panic

### PR DESCRIPTION
**Pull request by fadeevab**
Fixes the long-running issue #19.

@bodil

### CODE REVIEW

**Comment by fadeevab** [comment]
Come on, @bodil, why not? :)

**Comment by fadeevab** [comment]
@bodil Hi! Check this out, thanks 🥰

**Comment by fadeevab** [comment]
@bodil 👀

**Comment by bodil** [comment]
I appreciate your persistence. :+1:

**Comment by fadeevab** [comment]
@bodil Appreciate, thanks! 🫶 Have a nice great day!

**Pull request merged**
